#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 11, 2018 08:31:54 PM


import sys


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from tkinter import messagebox


import MySQLdb
#dataBase connection
db = MySQLdb.connect(host='35.204.26.147',user='root',passwd='ieee2018',db='ieee_uye')

cur = db.cursor()



def set_Tk_var():
    global txtSchoolID
    txtSchoolID = StringVar()
    global txtPassword
    txtPassword = StringVar()

def pushLogin():
    if(txtSchoolID.get()=="" or txtPassword.get()==""):
        if(txtSchoolID.get()==""):
            messagebox.showwarning("Empty School ID","Enter a School ID")
        else:
            messagebox.showwarning("Empty Password","Enter a password")
    if(txtSchoolID.get()!=""):
        command = "SELECT * FROM userList WHERE schoolID ="+txtSchoolID.get()+";"
        cur.execute(command)
        results = cur.fetchall()
        if(results!=()):
            for row in results:
                schoolID = row[0]
                name = row[1]
                surname = row[2]
                password = row[3]
                admin = row[4]
            if (txtPassword.get()==password):
                if(admin==b'\x01'):
                    messagebox.showinfo("Admin Login","Welcome "+name+" "+surname)
                else:
                    messagebox.showinfo("User Login","Welcome "+name+" "+surname)
            else:
                if(txtPassword.get()!=""):
                    messagebox.showwarning("Wrong","Wrong Password")
        else:
            messagebox.showwarning("Not found!","User not found")


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import login
    login.vp_start_gui()


