#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 11, 2018 08:31:46 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from tkinter import messagebox






import login_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.eval('tk::PlaceWindow %s center' % root.winfo_pathname(root.winfo_id()))#centers window
    login_support.set_Tk_var()
    top = IEEE_METU_NCC_Login (root)
    login_support.init(root, top)
    root.mainloop()

w = None
def create_IEEE_METU_NCC_Login(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    login_support.set_Tk_var()
    top = IEEE_METU_NCC_Login (w)
    login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_IEEE_METU_NCC_Login():
    global w
    w.destroy()
    w = None


class IEEE_METU_NCC_Login:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("290x147")
        top.title("IEEE METU NCC Login")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#f0f0f0f0f0f0")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.14, rely=0.2, height=21, width=62)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''School ID :''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.14, rely=0.48, height=21, width=62)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Password :''')

        self.TEntry1 = ttk.Entry(top)
        self.TEntry1.place(relx=0.41, rely=0.2, relheight=0.14, relwidth=0.43)
        self.TEntry1.configure(textvariable=login_support.txtSchoolID)
        self.TEntry1.configure(takefocus="")
        #self.TEntry1.configure(cursor="ibeam")
        self.TEntry1.focus()

        self.TEntry2 = ttk.Entry(top)
        self.TEntry2.place(relx=0.41, rely=0.48, relheight=0.14, relwidth=0.43)
        self.TEntry2.configure(textvariable=login_support.txtPassword)
        self.TEntry2.configure(takefocus="")
        #self.TEntry2.configure(cursor="ibeam")
        self.TEntry2.configure(show="*")

        self.TButton1 = ttk.Button(top)
        self.TButton1.place(relx=0.14, rely=0.68, height=25, width=206)
        self.TButton1.configure(command=login_support.pushLogin)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Login''')
        self.TButton1.configure(width=206)






if __name__ == '__main__':
    vp_start_gui()



