#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 15, 2018 05:51:30 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


from tkinter import messagebox

import MySQLdb
#dataBase connection
db = MySQLdb.connect(host='35.204.26.147',user='root',passwd='ieee2018',db='ieee_uye')

cur = db.cursor()

def set_Tk_var():
    global txtLoginSchoolID
    txtLoginSchoolID = StringVar()
    global txtLoginPassword
    txtLoginPassword = StringVar()
    global txtAddUID
    txtAddUID = StringVar()
    global txtAddName
    txtAddName = StringVar()
    global txtAddSurname
    txtAddSurname = StringVar()
    global txtAddSchoolID
    txtAddSchoolID = StringVar()
    global txtAddPhone
    txtAddPhone = StringVar()
    global txtLabelAddInfo
    txtLabelAddInfo = StringVar()
    global txtEditNum
    txtEditNum = StringVar()
    global txtEditUID
    txtEditUID = StringVar()
    global txtEditName
    txtEditName = StringVar()
    global txtEditSurname
    txtEditSurname = StringVar()
    global txtEditSchoolID
    txtEditSchoolID = StringVar()
    global txtEditPhone
    txtEditPhone = StringVar()
    global editCheck
    editCheck = StringVar()
    global txtLabelEditInfo
    txtLabelEditInfo = StringVar()
    global txtCreateEventName
    txtCreateEventName = StringVar()
    global txtCreateSociety
    txtCreateSociety = StringVar()
    global txtCreateDate
    txtCreateDate = StringVar()
    global txtLabelCreateInfo
    txtLabelCreateInfo = StringVar()
    global combobox
    combobox = StringVar()
    global txtAttendanceInfo
    txtAttendanceInfo = StringVar()
    global txtAttendUID
    txtAttendUID = StringVar()

def buttonAddReturn(p1):
    pushAddMemberButton()

def loginButtonReturn(p1):
    pushLoginButton()

def pushLoginButton():
    if(txtLoginSchoolID.get()=="" or txtLoginPassword.get()==""):
        if(txtLoginSchoolID.get()==""):
            messagebox.showwarning("Empty School ID","Enter a School ID")
        else:
            messagebox.showwarning("Empty Password","Enter a password")
    if(txtLoginSchoolID.get()!=""):
        command = "SELECT * FROM userList WHERE schoolID ="+txtLoginSchoolID.get()+";"
        cur.execute(command)
        results = cur.fetchall()
        if(results!=()):
            for row in results:
                schoolID = row[0]
                name = row[1]
                surname = row[2]
                password = row[3]
                admin = row[4]
            if (txtLoginPassword.get()==password):
                if(admin==b'\x01'):
                    messagebox.showinfo("Admin Login","Welcome "+name+" "+surname)
                    w.frameLogin.pack()
                    w.menubar.entryconfigure("Member Operations",state="normal")
                    w.menubar.entryconfigure("Event Operations",state="normal")
                    w.menubar.entryconfig("Change Password",state="normal")

                else:
                    messagebox.showinfo("User Login","Welcome "+name+" "+surname)
                    w.frameLogin.pack()
                    w.menubar.entryconfig("Change Password",state="normal")
            else:
                if(txtLoginPassword.get()!=""):
                    messagebox.showwarning("error!","Wrong password or schoolID")

        else:
            messagebox.showwarning("error!","Wrong password or schoolID")


def addUIDReturn(p1):
    command = "SELECT * FROM memberList WHERE UID ="+txtAddUID.get()+";"
    cur.execute(command)
    results = cur.fetchall()
    if(results!=()):
        for row in results:
                schoolID = row[0]
                name = row[1]
                surname = row[2]
                password = row[3]
                admin = row[4]
        messagebox.showwarning("Member Already Registered!",name+surname+" is already on the list!")
        txtAddUID.set("")
        w.TEntry3.focus()
    else:
        w.TEntry4.focus()
    

def pushAddMember():
    w.frameAddMember.place(relx=-0.01, rely=-0.02, relheight=1.05, relwidth=1.01)
    w.TEntry3.focus()
    w.menubar.entryconfigure("Member Operations",state="disabled")
    w.menubar.entryconfigure("Event Operations",state="disabled")
    w.menubar.entryconfig("Change Password",state="disabled")
    w.menubar.entryconfig("Main Menu",state="normal")
    txtAddPhone.set("")
    txtAddName.set("")
    txtAddSchoolID.set("")
    txtAddUID.set("")
    txtAddSurname.set("")


def pushAttendanceOK():
    if(combobox.get()!=""):
        w.frameTakeAttend.place(relx=0.3, rely=0.3, relheight=0.35, relwidth=.5)
        vals = combobox.get().strip().split(" ")
        global ID
        ID = int(vals[2])
    else:
        messagebox.showerror("Choose","Choose event")
    
def pushChangePassword():
    print('member_support.pushChangePassword')
    sys.stdout.flush()

def pushCreateEvent():
    w.frameCreateEvent.place(relx=-0.01, rely=-0.02, relheight=1.05, relwidth=1.01)
    w.menubar.entryconfigure("Member Operations",state="disabled")
    w.menubar.entryconfigure("Event Operations",state="disabled")
    w.menubar.entryconfig("Change Password",state="disabled")
    w.menubar.entryconfig("Main Menu",state="normal")
    w.TEntry14.focus()
    txtCreateEventName.set("")
    txtCreateDate.set("")
    txtCreateSociety.set("")

def pushButtonCreateEvent():
    command = "INSERT INTO eventList (name, society, date, members) VALUES ('"+txtCreateEventName.get()+"', '"+txtCreateSociety.get()+"', '"+txtCreateDate.get()+"', ' ');"
    cur.execute(command)
    db.commit()
    messagebox.showinfo("Created","Event created")

def pushEditCheck():
    if(editCheck.get()=="1"):
        w.entryEditName.configure(state="normal")
        w.entryEditUID.configure(state="normal")
        w.entryEditSurname.configure(state="normal")
        w.entryEditSchool.configure(state="disabled")
        w.entryEditPhone.configure(state="normal")
    else:
        w.entryEditName.configure(state="disabled")
        w.entryEditUID.configure(state="disabled")
        w.entryEditSurname.configure(state="disabled")
        w.entryEditSchool.configure(state="disabled")
        w.entryEditPhone.configure(state="disabled")


def editUIDSchoolReturn(p1):
    command = "SELECT * FROM memberList WHERE UID ="+txtEditNum.get()+";"
    cur.execute(command)
    results = cur.fetchall()
    command = "SELECT * FROM memberList WHERE schoolID ="+txtEditNum.get()+";"
    cur.execute(command)
    results1= cur.fetchall()
    if(results!=() or results1!=()):
        if(results!=()):
            for row in results:
                UID = row[0]
                name = row[1]
                surname = row[2]
                schoolID = row[3]
                phone = row[4]
        else:
            for row in results1:
                UID = row[0]
                name = row[1]
                surname = row[2]
                schoolID = row[3]
                phone = row[4] 
        txtEditName.set(name)
        txtEditSurname.set(surname)
        txtEditSchoolID.set(schoolID)
        txtEditUID.set(UID)
        txtEditPhone.set(phone)
    else:
        messagebox.showerror("Not Found!","Member not found!")


def pushEditMember():
    
    w.frameEditMember.place(relx=-0.01, rely=-0.02, relheight=1.05, relwidth=1.01)
    w.entryEditName.configure(state="disabled")
    w.entryEditUID.configure(state="disabled")
    w.entryEditSurname.configure(state="disabled")
    w.entryEditSchool.configure(state="disabled")
    w.entryEditPhone.configure(state="disabled")
    w.menubar.entryconfigure("Member Operations",state="disabled")
    w.menubar.entryconfigure("Event Operations",state="disabled")
    w.menubar.entryconfig("Change Password",state="disabled")
    w.menubar.entryconfig("Main Menu",state="normal")
    w.TEntry8.focus()
    txtEditNum.set("")
    txtEditName.set("")
    txtEditSurname.set("")
    txtEditSchoolID.set("")
    txtEditUID.set("")
    txtEditPhone.set("")
    editCheck.set("0")


def pushEditRemove():
    if(editCheck.get()!='1'):
        if(txtEditSchoolID.get()!=""):
            if (messagebox.askokcancel("Continue?","Member will be deleted?")):
                command = "DELETE FROM memberList WHERE schoolID ="+txtEditSchoolID.get()+";"
                cur.execute(command)
                db.commit()
                messagebox.showinfo("Succesful!","Succesfully deleted!")
                txtEditName.set("")
                txtEditSurname.set("")
                txtEditSchoolID.set("")
                txtEditUID.set("")
                txtEditPhone.set("")
        else:
            messagebox.showwarning("Error","Empty School ID!")
    else:
        messagebox.showwarning("Error","You are in editing mode!")
        w.TCheckbutton1.focus()


def pushEditSave():
    if(editCheck.get()=='1'):
        if (messagebox.askokcancel("Continue?","New credientals will be saved?")):
            command="UPDATE memberList SET UID='"+txtEditUID.get()+"', name='"+txtEditName.get()+"', surname='"+txtEditSurname.get()+"', phone='"+txtEditPhone.get()+"' WHERE schoolID="+txtEditSchoolID.get()+";"
            cur.execute(command)
            db.commit()
    else:
        messagebox.showwarning("Error","You are not in editing mode")


def pushEventList():
    print('member_support.pushEventList')
    sys.stdout.flush()

def pushAddMemberButton():
    adder = txtAddUID.get()+", '"+txtAddName.get()+"', '"+txtAddSurname.get()+"', "+txtAddSchoolID.get()+", '"+txtAddPhone.get()
    command = "SELECT * FROM memberList WHERE UID ="+txtAddUID.get()+";"
    cur.execute(command)
    results = cur.fetchall()
    if(results!=()):
        for row in results:
                schoolID = row[0]
                name = row[1]
                surname = row[2]
                password = row[3]
                admin = row[4]
        messagebox.showwarning("Member Already Registered!",name+" "+surname+" is already on the list!")
        txtAddUID.set("")
        txtAddName.set("")
        txtAddPhone.set("")
        txtAddSurname.set("")
        txtAddSchoolID.set("")
        w.TEntry3.focus()
    else:
        command = "INSERT INTO memberList (UID, name, surname, schoolID, phone) VALUES ("+adder+"');"
        cur.execute(command)
        db.commit()
        command="SELECT * FROM memberList WHERE UID ="+txtAddUID.get()+";"
        cur.execute(command)
        results = cur.fetchall()
        if(results!=()):
            for row in results:
                    UID = row[0]
                    name = row[1]
                    surname = row[2]
                    schoolID = row[3]
            messagebox.showinfo("Success!",UID+" "+name+" "+surname)
        else:
            messagebox.showerror("Error","Error not added!")
    txtLabelAddInfo.set(name+" "+surname+" added")
    txtAddName.set("")
    txtAddPhone.set("")
    txtAddSchoolID.set("")
    txtAddSurname.set("")
    txtAddUID.set("")
    w.TEntry3.focus()


def pushLogout():
    w.frameLogin.place(relx=-0.01, rely=-0.02, relheight=1.05, relwidth=1.01)
    txtLoginSchoolID.set("")
    txtLoginPassword.set("")
    w.menubar.entryconfigure("Member Operations",state="disabled")
    w.menubar.entryconfigure("Event Operations",state="disabled")
    w.menubar.entryconfig("Change Password",state="disabled")
    w.menubar.entryconfig("Main Menu",state="disabled")
    w.TEntry1.focus()


def pushMainMenu():
    w.frameLogin.place(relx=-0.01, rely=-0.02, relheight=0, relwidth=0)
    w.frameAddMember.place(relx=-0.01, rely=-0.02, relheight=0, relwidth=0)
    w.frameAttendance.place(relx=-0.01, rely=-0.02, relheight=0, relwidth=0)
    w.frameCreateEvent.place(relx=-0.01, rely=-0.02, relheight=0, relwidth=0)
    w.frameEditMember.place(relx=-0.01, rely=-0.02, relheight=0, relwidth=0)
    w.framePassword.place(relx=-0.01, rely=-0.02, relheight=0, relwidth=0)
    w.frameTakeAttend.place(relx=-0.01, rely=-0.02, relheight=0, relwidth=0)
    w.menubar.entryconfigure("Member Operations",state="normal")
    w.menubar.entryconfigure("Event Operations",state="normal")
    w.menubar.entryconfig("Change Password",state="normal")
    w.menubar.entryconfig("Main Menu",state="disabled")


def pushMemberList():
    print('member_support.pushMemberList')
    sys.stdout.flush()

def pushSavePassword():
    print('member_support.pushSavePassword')
    sys.stdout.flush()

def pushTakeAttend():
    w.frameAttendance.place(relx=-0.01, rely=-0.02, relheight=1.05, relwidth=1.01)
    w.menubar.entryconfigure("Member Operations",state="disabled")
    w.menubar.entryconfigure("Event Operations",state="disabled")
    w.menubar.entryconfig("Change Password",state="disabled")
    w.menubar.entryconfig("Main Menu",state="normal") 
    command = "SELECT date, name, ID FROM eventList;"
    cur.execute(command)
    results = cur.fetchall() 
    w.value_list=results
    w.TCombobox1.configure(values=w.value_list)

def takeAttendUIDReturn(p1):
    command = "SELECT * FROM memberList WHERE UID ='"+txtAttendUID.get()+"';"
    print(txtAttendUID.get())
    cur.execute(command)
    results = cur.fetchall()
    for row in results:
        name = row[1]
        surname = row[2]
    print(results)
    if(results!=()):
        for row in results:
            schoolID = row[3]
        command = "SELECT * FROM eventList WHERE ID ="+str(ID)+";"
        cur.execute(command)
        results = cur.fetchall()
        print(results)
        for row in results:
            members = row[4]
        command="UPDATE eventList SET members='"+str(members)+"' '"+" "+str(schoolID)+"' WHERE ID='"+str(ID)+"';"
        cur.execute(command)
        db.commit()
        txtAttendanceInfo.set(name + " " +surname+" added!")
        txtAttendUID.set("")
        w.TEntry17.focus()
    else:
        messagebox.showerror("Not on the list","UID not on the list")

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import member
    member.vp_start_gui()


